#!/usr/bin/env python

import click
import sys
from os import path

from pybuilder_demo.main import start


@click.command()
@click.option('--arg1', prompt=True, help='arg1 Description')
@click.option('--arg2', prompt=True, help='arg2 Description')
@click.option('--conf', default='{0}/etc/configs'.format(path.dirname(path.dirname(__file__))),
              prompt=True, help='Config directory absolute Path')
def run(arg1, arg2, conf):
    start(str(arg1), str(arg2), str(conf))


if __name__ == '__main__':
    sys.exit(run())
